move_service_node:
  ros__parameters:
    topic_tracing_move: /papjia/move/line_tracing
    topic_tracing_trigger: /papjia/move/line_tracing_trigger
    topic_straight_move: /papjia/move/straight_move
    topic_odom: /odom
    topic_cmd_vel: /cmd_vel_smoothed
    default_speed: 0.2
    use_stamp_twist: false
    enable_tracing: true
    enable_move: true

