TYPE_MAPPING = {
    "float64": "double",
    "float32": "float",
    "int64": "int64_t",
    "int32": "int32_t",
    "int16": "int16_t",
    "int8": "int8_t",
    "uint64": "uint64_t",
    "uint32": "uint32_t",
    "uint16": "uint16_t",
    "uint8": "uint8_t",
    "bool": "bool",
    "string": "std::string",
    "string[]": "std::vector<std::string>",
    "float64[]": "std::vector<double>",
    "float32[]": "std::vector<float>",
    "int64[]": "std::vector<int64_t>",
    "int32[]": "std::vector<int32_t>",
    "int16[]": "std::vector<int16_t>",
    "int8[]": "std::vector<int8_t>",
    "uint64[]": "std::vector<uint64_t>",
    "uint32[]": "std::vector<uint32_t>",
    "uint16[]": "std::vector<uint16_t>",
    "sensor_msgs/Image": "sensor_msgs::msg::Image",
    "sensor_msgs/CameraInfo": "sensor_msgs::msg::CameraInfo",
}
