# Default initial positions for melon_grasper's ros2_control fake system

initial_positions:
  arm_joint1: 1.57
  arm_joint2: -1.0
  arm_joint3: 2.37
  arm_joint4: -1.57
  arm_joint5: -1.8
  arm_joint6: 0.0