#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class StateRobot(object):
    SR_Start = 0
    SR_Initialize = 1
    SR_Logout = 2
    SR_Login = 3
    SR_PowerOff = 4
    SR_Disable = 5
    SR_Enable = 6

    _VALUES_TO_NAMES = {
        0: "SR_Start",
        1: "SR_Initialize",
        2: "SR_Logout",
        3: "SR_Login",
        4: "SR_PowerOff",
        5: "SR_Disable",
        6: "SR_Enable",
    }

    _NAMES_TO_VALUES = {
        "SR_Start": 0,
        "SR_Initialize": 1,
        "SR_Logout": 2,
        "SR_Login": 3,
        "SR_PowerOff": 4,
        "SR_Disable": 5,
        "SR_Enable": 6,
    }


class StateProgram(object):
    SP_Stopped = 0
    SP_Stopping = 1
    SP_Running = 2
    SP_Paused = 3
    SP_Pausing = 4

    _VALUES_TO_NAMES = {
        0: "SP_Stopped",
        1: "SP_Stopping",
        2: "SP_Running",
        3: "SP_Paused",
        4: "SP_Pausing",
    }

    _NAMES_TO_VALUES = {
        "SP_Stopped": 0,
        "SP_Stopping": 1,
        "SP_Running": 2,
        "SP_Paused": 3,
        "SP_Pausing": 4,
    }


class OperationMode(object):
    kManual = 0
    kAuto = 1
    kRemote = 2

    _VALUES_TO_NAMES = {
        0: "kManual",
        1: "kAuto",
        2: "kRemote",
    }

    _NAMES_TO_VALUES = {
        "kManual": 0,
        "kAuto": 1,
        "kRemote": 2,
    }


class TaskState(object):
    ST_Idle = 0
    ST_Running = 1
    ST_Paused = 2
    ST_Stopped = 3
    ST_Finished = 4
    ST_Interrupt = 5
    ST_Error = 6
    ST_Illegal = 7
    ST_ParameterMismatch = 8

    _VALUES_TO_NAMES = {
        0: "ST_Idle",
        1: "ST_Running",
        2: "ST_Paused",
        3: "ST_Stopped",
        4: "ST_Finished",
        5: "ST_Interrupt",
        6: "ST_Error",
        7: "ST_Illegal",
        8: "ST_ParameterMismatch",
    }

    _NAMES_TO_VALUES = {
        "ST_Idle": 0,
        "ST_Running": 1,
        "ST_Paused": 2,
        "ST_Stopped": 3,
        "ST_Finished": 4,
        "ST_Interrupt": 5,
        "ST_Error": 6,
        "ST_Illegal": 7,
        "ST_ParameterMismatch": 8,
    }


class SafetyState(object):
    SS_INIT = 0
    SS_WAIT = 2
    SS_CONFIG = 3
    SS_POWER_OFF = 4
    SS_RUN = 5
    SS_RECOVERY = 6
    SS_STOP2 = 7
    SS_STOP1 = 8
    SS_STOP0 = 9
    SS_MODEL = 10
    SS_REDUCE = 12
    SS_BOOT = 13
    SS_FAIL = 14
    SS_UPDATE = 99

    _VALUES_TO_NAMES = {
        0: "SS_INIT",
        2: "SS_WAIT",
        3: "SS_CONFIG",
        4: "SS_POWER_OFF",
        5: "SS_RUN",
        6: "SS_RECOVERY",
        7: "SS_STOP2",
        8: "SS_STOP1",
        9: "SS_STOP0",
        10: "SS_MODEL",
        12: "SS_REDUCE",
        13: "SS_BOOT",
        14: "SS_FAIL",
        99: "SS_UPDATE",
    }

    _NAMES_TO_VALUES = {
        "SS_INIT": 0,
        "SS_WAIT": 2,
        "SS_CONFIG": 3,
        "SS_POWER_OFF": 4,
        "SS_RUN": 5,
        "SS_RECOVERY": 6,
        "SS_STOP2": 7,
        "SS_STOP1": 8,
        "SS_STOP0": 9,
        "SS_MODEL": 10,
        "SS_REDUCE": 12,
        "SS_BOOT": 13,
        "SS_FAIL": 14,
        "SS_UPDATE": 99,
    }


class Op(object):
    """
    Attributes:
     - time_or_dist_1
     - trig_io_1
     - trig_value_1
     - trig_time_1
     - trig_dist_1
     - trig_event_1
     - time_or_dist_2
     - trig_io_2
     - trig_value_2
     - trig_time_2
     - trig_dist_2
     - trig_event_2

    """


    def __init__(self, time_or_dist_1=None, trig_io_1=None, trig_value_1=None, trig_time_1=None, trig_dist_1=None, trig_event_1=None, time_or_dist_2=None, trig_io_2=None, trig_value_2=None, trig_time_2=None, trig_dist_2=None, trig_event_2=None,):
        self.time_or_dist_1 = time_or_dist_1
        self.trig_io_1 = trig_io_1
        self.trig_value_1 = trig_value_1
        self.trig_time_1 = trig_time_1
        self.trig_dist_1 = trig_dist_1
        self.trig_event_1 = trig_event_1
        self.time_or_dist_2 = time_or_dist_2
        self.trig_io_2 = trig_io_2
        self.trig_value_2 = trig_value_2
        self.trig_time_2 = trig_time_2
        self.trig_dist_2 = trig_dist_2
        self.trig_event_2 = trig_event_2

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.BYTE:
                    self.time_or_dist_1 = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.BYTE:
                    self.trig_io_1 = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.BOOL:
                    self.trig_value_1 = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.DOUBLE:
                    self.trig_time_1 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.DOUBLE:
                    self.trig_dist_1 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.trig_event_1 = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.BYTE:
                    self.time_or_dist_2 = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.BYTE:
                    self.trig_io_2 = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.BOOL:
                    self.trig_value_2 = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.DOUBLE:
                    self.trig_time_2 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 11:
                if ftype == TType.DOUBLE:
                    self.trig_dist_2 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 12:
                if ftype == TType.STRING:
                    self.trig_event_2 = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Op')
        if self.time_or_dist_1 is not None:
            oprot.writeFieldBegin('time_or_dist_1', TType.BYTE, 1)
            oprot.writeByte(self.time_or_dist_1)
            oprot.writeFieldEnd()
        if self.trig_io_1 is not None:
            oprot.writeFieldBegin('trig_io_1', TType.BYTE, 2)
            oprot.writeByte(self.trig_io_1)
            oprot.writeFieldEnd()
        if self.trig_value_1 is not None:
            oprot.writeFieldBegin('trig_value_1', TType.BOOL, 3)
            oprot.writeBool(self.trig_value_1)
            oprot.writeFieldEnd()
        if self.trig_time_1 is not None:
            oprot.writeFieldBegin('trig_time_1', TType.DOUBLE, 4)
            oprot.writeDouble(self.trig_time_1)
            oprot.writeFieldEnd()
        if self.trig_dist_1 is not None:
            oprot.writeFieldBegin('trig_dist_1', TType.DOUBLE, 5)
            oprot.writeDouble(self.trig_dist_1)
            oprot.writeFieldEnd()
        if self.trig_event_1 is not None:
            oprot.writeFieldBegin('trig_event_1', TType.STRING, 6)
            oprot.writeString(self.trig_event_1.encode('utf-8') if sys.version_info[0] == 2 else self.trig_event_1)
            oprot.writeFieldEnd()
        if self.time_or_dist_2 is not None:
            oprot.writeFieldBegin('time_or_dist_2', TType.BYTE, 7)
            oprot.writeByte(self.time_or_dist_2)
            oprot.writeFieldEnd()
        if self.trig_io_2 is not None:
            oprot.writeFieldBegin('trig_io_2', TType.BYTE, 8)
            oprot.writeByte(self.trig_io_2)
            oprot.writeFieldEnd()
        if self.trig_value_2 is not None:
            oprot.writeFieldBegin('trig_value_2', TType.BOOL, 9)
            oprot.writeBool(self.trig_value_2)
            oprot.writeFieldEnd()
        if self.trig_time_2 is not None:
            oprot.writeFieldBegin('trig_time_2', TType.DOUBLE, 10)
            oprot.writeDouble(self.trig_time_2)
            oprot.writeFieldEnd()
        if self.trig_dist_2 is not None:
            oprot.writeFieldBegin('trig_dist_2', TType.DOUBLE, 11)
            oprot.writeDouble(self.trig_dist_2)
            oprot.writeFieldEnd()
        if self.trig_event_2 is not None:
            oprot.writeFieldBegin('trig_event_2', TType.STRING, 12)
            oprot.writeString(self.trig_event_2.encode('utf-8') if sys.version_info[0] == 2 else self.trig_event_2)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.time_or_dist_1 is None:
            raise TProtocolException(message='Required field time_or_dist_1 is unset!')
        if self.trig_io_1 is None:
            raise TProtocolException(message='Required field trig_io_1 is unset!')
        if self.trig_value_1 is None:
            raise TProtocolException(message='Required field trig_value_1 is unset!')
        if self.trig_time_1 is None:
            raise TProtocolException(message='Required field trig_time_1 is unset!')
        if self.trig_dist_1 is None:
            raise TProtocolException(message='Required field trig_dist_1 is unset!')
        if self.trig_event_1 is None:
            raise TProtocolException(message='Required field trig_event_1 is unset!')
        if self.time_or_dist_2 is None:
            raise TProtocolException(message='Required field time_or_dist_2 is unset!')
        if self.trig_io_2 is None:
            raise TProtocolException(message='Required field trig_io_2 is unset!')
        if self.trig_value_2 is None:
            raise TProtocolException(message='Required field trig_value_2 is unset!')
        if self.trig_time_2 is None:
            raise TProtocolException(message='Required field trig_time_2 is unset!')
        if self.trig_dist_2 is None:
            raise TProtocolException(message='Required field trig_dist_2 is unset!')
        if self.trig_event_2 is None:
            raise TProtocolException(message='Required field trig_event_2 is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class RobotStatus(object):
    """
    Attributes:
     - jointExpectPosition
     - jointExpectVelocity
     - jointExpectAccelera
     - jointActualPosition
     - jointActualVelocity
     - jointActualAccelera
     - jointActualCurrent
     - jointTemperature
     - driverTemperature
     - cartExpectPosition
     - cartExpectVelocity
     - cartExpectAccelera
     - cartActualPosition
     - cartActualVelocity
     - cartActualAccelera
     - slaveReady
     - collision
     - collisionAxis
     - emcStopSignal
     - robotState
     - robotError

    """


    def __init__(self, jointExpectPosition=None, jointExpectVelocity=None, jointExpectAccelera=None, jointActualPosition=None, jointActualVelocity=None, jointActualAccelera=None, jointActualCurrent=None, jointTemperature=None, driverTemperature=None, cartExpectPosition=None, cartExpectVelocity=None, cartExpectAccelera=None, cartActualPosition=None, cartActualVelocity=None, cartActualAccelera=None, slaveReady=None, collision=None, collisionAxis=None, emcStopSignal=None, robotState=None, robotError=None,):
        self.jointExpectPosition = jointExpectPosition
        self.jointExpectVelocity = jointExpectVelocity
        self.jointExpectAccelera = jointExpectAccelera
        self.jointActualPosition = jointActualPosition
        self.jointActualVelocity = jointActualVelocity
        self.jointActualAccelera = jointActualAccelera
        self.jointActualCurrent = jointActualCurrent
        self.jointTemperature = jointTemperature
        self.driverTemperature = driverTemperature
        self.cartExpectPosition = cartExpectPosition
        self.cartExpectVelocity = cartExpectVelocity
        self.cartExpectAccelera = cartExpectAccelera
        self.cartActualPosition = cartActualPosition
        self.cartActualVelocity = cartActualVelocity
        self.cartActualAccelera = cartActualAccelera
        self.slaveReady = slaveReady
        self.collision = collision
        self.collisionAxis = collisionAxis
        self.emcStopSignal = emcStopSignal
        self.robotState = robotState
        self.robotError = robotError

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.LIST:
                    self.jointExpectPosition = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = iprot.readDouble()
                        self.jointExpectPosition.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.LIST:
                    self.jointExpectVelocity = []
                    (_etype9, _size6) = iprot.readListBegin()
                    for _i10 in range(_size6):
                        _elem11 = iprot.readDouble()
                        self.jointExpectVelocity.append(_elem11)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.LIST:
                    self.jointExpectAccelera = []
                    (_etype15, _size12) = iprot.readListBegin()
                    for _i16 in range(_size12):
                        _elem17 = iprot.readDouble()
                        self.jointExpectAccelera.append(_elem17)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.LIST:
                    self.jointActualPosition = []
                    (_etype21, _size18) = iprot.readListBegin()
                    for _i22 in range(_size18):
                        _elem23 = iprot.readDouble()
                        self.jointActualPosition.append(_elem23)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.LIST:
                    self.jointActualVelocity = []
                    (_etype27, _size24) = iprot.readListBegin()
                    for _i28 in range(_size24):
                        _elem29 = iprot.readDouble()
                        self.jointActualVelocity.append(_elem29)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.LIST:
                    self.jointActualAccelera = []
                    (_etype33, _size30) = iprot.readListBegin()
                    for _i34 in range(_size30):
                        _elem35 = iprot.readDouble()
                        self.jointActualAccelera.append(_elem35)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.LIST:
                    self.jointActualCurrent = []
                    (_etype39, _size36) = iprot.readListBegin()
                    for _i40 in range(_size36):
                        _elem41 = iprot.readDouble()
                        self.jointActualCurrent.append(_elem41)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.LIST:
                    self.jointTemperature = []
                    (_etype45, _size42) = iprot.readListBegin()
                    for _i46 in range(_size42):
                        _elem47 = iprot.readDouble()
                        self.jointTemperature.append(_elem47)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.LIST:
                    self.driverTemperature = []
                    (_etype51, _size48) = iprot.readListBegin()
                    for _i52 in range(_size48):
                        _elem53 = iprot.readDouble()
                        self.driverTemperature.append(_elem53)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.LIST:
                    self.cartExpectPosition = []
                    (_etype57, _size54) = iprot.readListBegin()
                    for _i58 in range(_size54):
                        _elem59 = iprot.readDouble()
                        self.cartExpectPosition.append(_elem59)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 11:
                if ftype == TType.LIST:
                    self.cartExpectVelocity = []
                    (_etype63, _size60) = iprot.readListBegin()
                    for _i64 in range(_size60):
                        _elem65 = iprot.readDouble()
                        self.cartExpectVelocity.append(_elem65)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 12:
                if ftype == TType.LIST:
                    self.cartExpectAccelera = []
                    (_etype69, _size66) = iprot.readListBegin()
                    for _i70 in range(_size66):
                        _elem71 = iprot.readDouble()
                        self.cartExpectAccelera.append(_elem71)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 13:
                if ftype == TType.LIST:
                    self.cartActualPosition = []
                    (_etype75, _size72) = iprot.readListBegin()
                    for _i76 in range(_size72):
                        _elem77 = iprot.readDouble()
                        self.cartActualPosition.append(_elem77)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 14:
                if ftype == TType.LIST:
                    self.cartActualVelocity = []
                    (_etype81, _size78) = iprot.readListBegin()
                    for _i82 in range(_size78):
                        _elem83 = iprot.readDouble()
                        self.cartActualVelocity.append(_elem83)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 15:
                if ftype == TType.LIST:
                    self.cartActualAccelera = []
                    (_etype87, _size84) = iprot.readListBegin()
                    for _i88 in range(_size84):
                        _elem89 = iprot.readDouble()
                        self.cartActualAccelera.append(_elem89)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 16:
                if ftype == TType.LIST:
                    self.slaveReady = []
                    (_etype93, _size90) = iprot.readListBegin()
                    for _i94 in range(_size90):
                        _elem95 = iprot.readBool()
                        self.slaveReady.append(_elem95)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 17:
                if ftype == TType.BOOL:
                    self.collision = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 18:
                if ftype == TType.BYTE:
                    self.collisionAxis = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 19:
                if ftype == TType.BOOL:
                    self.emcStopSignal = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 20:
                if ftype == TType.BYTE:
                    self.robotState = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 21:
                if ftype == TType.I32:
                    self.robotError = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('RobotStatus')
        if self.jointExpectPosition is not None:
            oprot.writeFieldBegin('jointExpectPosition', TType.LIST, 1)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointExpectPosition))
            for iter96 in self.jointExpectPosition:
                oprot.writeDouble(iter96)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.jointExpectVelocity is not None:
            oprot.writeFieldBegin('jointExpectVelocity', TType.LIST, 2)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointExpectVelocity))
            for iter97 in self.jointExpectVelocity:
                oprot.writeDouble(iter97)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.jointExpectAccelera is not None:
            oprot.writeFieldBegin('jointExpectAccelera', TType.LIST, 3)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointExpectAccelera))
            for iter98 in self.jointExpectAccelera:
                oprot.writeDouble(iter98)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.jointActualPosition is not None:
            oprot.writeFieldBegin('jointActualPosition', TType.LIST, 4)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointActualPosition))
            for iter99 in self.jointActualPosition:
                oprot.writeDouble(iter99)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.jointActualVelocity is not None:
            oprot.writeFieldBegin('jointActualVelocity', TType.LIST, 5)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointActualVelocity))
            for iter100 in self.jointActualVelocity:
                oprot.writeDouble(iter100)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.jointActualAccelera is not None:
            oprot.writeFieldBegin('jointActualAccelera', TType.LIST, 6)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointActualAccelera))
            for iter101 in self.jointActualAccelera:
                oprot.writeDouble(iter101)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.jointActualCurrent is not None:
            oprot.writeFieldBegin('jointActualCurrent', TType.LIST, 7)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointActualCurrent))
            for iter102 in self.jointActualCurrent:
                oprot.writeDouble(iter102)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.jointTemperature is not None:
            oprot.writeFieldBegin('jointTemperature', TType.LIST, 8)
            oprot.writeListBegin(TType.DOUBLE, len(self.jointTemperature))
            for iter103 in self.jointTemperature:
                oprot.writeDouble(iter103)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.driverTemperature is not None:
            oprot.writeFieldBegin('driverTemperature', TType.LIST, 9)
            oprot.writeListBegin(TType.DOUBLE, len(self.driverTemperature))
            for iter104 in self.driverTemperature:
                oprot.writeDouble(iter104)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.cartExpectPosition is not None:
            oprot.writeFieldBegin('cartExpectPosition', TType.LIST, 10)
            oprot.writeListBegin(TType.DOUBLE, len(self.cartExpectPosition))
            for iter105 in self.cartExpectPosition:
                oprot.writeDouble(iter105)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.cartExpectVelocity is not None:
            oprot.writeFieldBegin('cartExpectVelocity', TType.LIST, 11)
            oprot.writeListBegin(TType.DOUBLE, len(self.cartExpectVelocity))
            for iter106 in self.cartExpectVelocity:
                oprot.writeDouble(iter106)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.cartExpectAccelera is not None:
            oprot.writeFieldBegin('cartExpectAccelera', TType.LIST, 12)
            oprot.writeListBegin(TType.DOUBLE, len(self.cartExpectAccelera))
            for iter107 in self.cartExpectAccelera:
                oprot.writeDouble(iter107)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.cartActualPosition is not None:
            oprot.writeFieldBegin('cartActualPosition', TType.LIST, 13)
            oprot.writeListBegin(TType.DOUBLE, len(self.cartActualPosition))
            for iter108 in self.cartActualPosition:
                oprot.writeDouble(iter108)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.cartActualVelocity is not None:
            oprot.writeFieldBegin('cartActualVelocity', TType.LIST, 14)
            oprot.writeListBegin(TType.DOUBLE, len(self.cartActualVelocity))
            for iter109 in self.cartActualVelocity:
                oprot.writeDouble(iter109)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.cartActualAccelera is not None:
            oprot.writeFieldBegin('cartActualAccelera', TType.LIST, 15)
            oprot.writeListBegin(TType.DOUBLE, len(self.cartActualAccelera))
            for iter110 in self.cartActualAccelera:
                oprot.writeDouble(iter110)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.slaveReady is not None:
            oprot.writeFieldBegin('slaveReady', TType.LIST, 16)
            oprot.writeListBegin(TType.BOOL, len(self.slaveReady))
            for iter111 in self.slaveReady:
                oprot.writeBool(iter111)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.collision is not None:
            oprot.writeFieldBegin('collision', TType.BOOL, 17)
            oprot.writeBool(self.collision)
            oprot.writeFieldEnd()
        if self.collisionAxis is not None:
            oprot.writeFieldBegin('collisionAxis', TType.BYTE, 18)
            oprot.writeByte(self.collisionAxis)
            oprot.writeFieldEnd()
        if self.emcStopSignal is not None:
            oprot.writeFieldBegin('emcStopSignal', TType.BOOL, 19)
            oprot.writeBool(self.emcStopSignal)
            oprot.writeFieldEnd()
        if self.robotState is not None:
            oprot.writeFieldBegin('robotState', TType.BYTE, 20)
            oprot.writeByte(self.robotState)
            oprot.writeFieldEnd()
        if self.robotError is not None:
            oprot.writeFieldBegin('robotError', TType.I32, 21)
            oprot.writeI32(self.robotError)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.jointExpectPosition is None:
            raise TProtocolException(message='Required field jointExpectPosition is unset!')
        if self.jointExpectVelocity is None:
            raise TProtocolException(message='Required field jointExpectVelocity is unset!')
        if self.jointExpectAccelera is None:
            raise TProtocolException(message='Required field jointExpectAccelera is unset!')
        if self.jointActualPosition is None:
            raise TProtocolException(message='Required field jointActualPosition is unset!')
        if self.jointActualVelocity is None:
            raise TProtocolException(message='Required field jointActualVelocity is unset!')
        if self.jointActualAccelera is None:
            raise TProtocolException(message='Required field jointActualAccelera is unset!')
        if self.jointActualCurrent is None:
            raise TProtocolException(message='Required field jointActualCurrent is unset!')
        if self.jointTemperature is None:
            raise TProtocolException(message='Required field jointTemperature is unset!')
        if self.driverTemperature is None:
            raise TProtocolException(message='Required field driverTemperature is unset!')
        if self.cartExpectPosition is None:
            raise TProtocolException(message='Required field cartExpectPosition is unset!')
        if self.cartExpectVelocity is None:
            raise TProtocolException(message='Required field cartExpectVelocity is unset!')
        if self.cartExpectAccelera is None:
            raise TProtocolException(message='Required field cartExpectAccelera is unset!')
        if self.cartActualPosition is None:
            raise TProtocolException(message='Required field cartActualPosition is unset!')
        if self.cartActualVelocity is None:
            raise TProtocolException(message='Required field cartActualVelocity is unset!')
        if self.cartActualAccelera is None:
            raise TProtocolException(message='Required field cartActualAccelera is unset!')
        if self.slaveReady is None:
            raise TProtocolException(message='Required field slaveReady is unset!')
        if self.collision is None:
            raise TProtocolException(message='Required field collision is unset!')
        if self.collisionAxis is None:
            raise TProtocolException(message='Required field collisionAxis is unset!')
        if self.emcStopSignal is None:
            raise TProtocolException(message='Required field emcStopSignal is unset!')
        if self.robotState is None:
            raise TProtocolException(message='Required field robotState is unset!')
        if self.robotError is None:
            raise TProtocolException(message='Required field robotError is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class IOStatus(object):
    """
    Attributes:
     - analogCurrentOutputs
     - analogVoltageOutputs
     - digitalInputs
     - digitalOutputs
     - toolIOIn
     - toolIOOut
     - toolButton

    """


    def __init__(self, analogCurrentOutputs=None, analogVoltageOutputs=None, digitalInputs=None, digitalOutputs=None, toolIOIn=None, toolIOOut=None, toolButton=None,):
        self.analogCurrentOutputs = analogCurrentOutputs
        self.analogVoltageOutputs = analogVoltageOutputs
        self.digitalInputs = digitalInputs
        self.digitalOutputs = digitalOutputs
        self.toolIOIn = toolIOIn
        self.toolIOOut = toolIOOut
        self.toolButton = toolButton

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.LIST:
                    self.analogCurrentOutputs = []
                    (_etype115, _size112) = iprot.readListBegin()
                    for _i116 in range(_size112):
                        _elem117 = iprot.readDouble()
                        self.analogCurrentOutputs.append(_elem117)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.LIST:
                    self.analogVoltageOutputs = []
                    (_etype121, _size118) = iprot.readListBegin()
                    for _i122 in range(_size118):
                        _elem123 = iprot.readDouble()
                        self.analogVoltageOutputs.append(_elem123)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.LIST:
                    self.digitalInputs = []
                    (_etype127, _size124) = iprot.readListBegin()
                    for _i128 in range(_size124):
                        _elem129 = iprot.readBool()
                        self.digitalInputs.append(_elem129)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.LIST:
                    self.digitalOutputs = []
                    (_etype133, _size130) = iprot.readListBegin()
                    for _i134 in range(_size130):
                        _elem135 = iprot.readBool()
                        self.digitalOutputs.append(_elem135)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.LIST:
                    self.toolIOIn = []
                    (_etype139, _size136) = iprot.readListBegin()
                    for _i140 in range(_size136):
                        _elem141 = iprot.readBool()
                        self.toolIOIn.append(_elem141)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.LIST:
                    self.toolIOOut = []
                    (_etype145, _size142) = iprot.readListBegin()
                    for _i146 in range(_size142):
                        _elem147 = iprot.readBool()
                        self.toolIOOut.append(_elem147)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.LIST:
                    self.toolButton = []
                    (_etype151, _size148) = iprot.readListBegin()
                    for _i152 in range(_size148):
                        _elem153 = iprot.readBool()
                        self.toolButton.append(_elem153)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('IOStatus')
        if self.analogCurrentOutputs is not None:
            oprot.writeFieldBegin('analogCurrentOutputs', TType.LIST, 1)
            oprot.writeListBegin(TType.DOUBLE, len(self.analogCurrentOutputs))
            for iter154 in self.analogCurrentOutputs:
                oprot.writeDouble(iter154)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.analogVoltageOutputs is not None:
            oprot.writeFieldBegin('analogVoltageOutputs', TType.LIST, 2)
            oprot.writeListBegin(TType.DOUBLE, len(self.analogVoltageOutputs))
            for iter155 in self.analogVoltageOutputs:
                oprot.writeDouble(iter155)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.digitalInputs is not None:
            oprot.writeFieldBegin('digitalInputs', TType.LIST, 3)
            oprot.writeListBegin(TType.BOOL, len(self.digitalInputs))
            for iter156 in self.digitalInputs:
                oprot.writeBool(iter156)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.digitalOutputs is not None:
            oprot.writeFieldBegin('digitalOutputs', TType.LIST, 4)
            oprot.writeListBegin(TType.BOOL, len(self.digitalOutputs))
            for iter157 in self.digitalOutputs:
                oprot.writeBool(iter157)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.toolIOIn is not None:
            oprot.writeFieldBegin('toolIOIn', TType.LIST, 5)
            oprot.writeListBegin(TType.BOOL, len(self.toolIOIn))
            for iter158 in self.toolIOIn:
                oprot.writeBool(iter158)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.toolIOOut is not None:
            oprot.writeFieldBegin('toolIOOut', TType.LIST, 6)
            oprot.writeListBegin(TType.BOOL, len(self.toolIOOut))
            for iter159 in self.toolIOOut:
                oprot.writeBool(iter159)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.toolButton is not None:
            oprot.writeFieldBegin('toolButton', TType.LIST, 7)
            oprot.writeListBegin(TType.BOOL, len(self.toolButton))
            for iter160 in self.toolButton:
                oprot.writeBool(iter160)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.analogCurrentOutputs is None:
            raise TProtocolException(message='Required field analogCurrentOutputs is unset!')
        if self.analogVoltageOutputs is None:
            raise TProtocolException(message='Required field analogVoltageOutputs is unset!')
        if self.digitalInputs is None:
            raise TProtocolException(message='Required field digitalInputs is unset!')
        if self.digitalOutputs is None:
            raise TProtocolException(message='Required field digitalOutputs is unset!')
        if self.toolIOIn is None:
            raise TProtocolException(message='Required field toolIOIn is unset!')
        if self.toolIOOut is None:
            raise TProtocolException(message='Required field toolIOOut is unset!')
        if self.toolButton is None:
            raise TProtocolException(message='Required field toolButton is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(Op)
Op.thrift_spec = (
    None,  # 0
    (1, TType.BYTE, 'time_or_dist_1', None, None, ),  # 1
    (2, TType.BYTE, 'trig_io_1', None, None, ),  # 2
    (3, TType.BOOL, 'trig_value_1', None, None, ),  # 3
    (4, TType.DOUBLE, 'trig_time_1', None, None, ),  # 4
    (5, TType.DOUBLE, 'trig_dist_1', None, None, ),  # 5
    (6, TType.STRING, 'trig_event_1', 'UTF8', None, ),  # 6
    (7, TType.BYTE, 'time_or_dist_2', None, None, ),  # 7
    (8, TType.BYTE, 'trig_io_2', None, None, ),  # 8
    (9, TType.BOOL, 'trig_value_2', None, None, ),  # 9
    (10, TType.DOUBLE, 'trig_time_2', None, None, ),  # 10
    (11, TType.DOUBLE, 'trig_dist_2', None, None, ),  # 11
    (12, TType.STRING, 'trig_event_2', 'UTF8', None, ),  # 12
)
all_structs.append(RobotStatus)
RobotStatus.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'jointExpectPosition', (TType.DOUBLE, None, False), None, ),  # 1
    (2, TType.LIST, 'jointExpectVelocity', (TType.DOUBLE, None, False), None, ),  # 2
    (3, TType.LIST, 'jointExpectAccelera', (TType.DOUBLE, None, False), None, ),  # 3
    (4, TType.LIST, 'jointActualPosition', (TType.DOUBLE, None, False), None, ),  # 4
    (5, TType.LIST, 'jointActualVelocity', (TType.DOUBLE, None, False), None, ),  # 5
    (6, TType.LIST, 'jointActualAccelera', (TType.DOUBLE, None, False), None, ),  # 6
    (7, TType.LIST, 'jointActualCurrent', (TType.DOUBLE, None, False), None, ),  # 7
    (8, TType.LIST, 'jointTemperature', (TType.DOUBLE, None, False), None, ),  # 8
    (9, TType.LIST, 'driverTemperature', (TType.DOUBLE, None, False), None, ),  # 9
    (10, TType.LIST, 'cartExpectPosition', (TType.DOUBLE, None, False), None, ),  # 10
    (11, TType.LIST, 'cartExpectVelocity', (TType.DOUBLE, None, False), None, ),  # 11
    (12, TType.LIST, 'cartExpectAccelera', (TType.DOUBLE, None, False), None, ),  # 12
    (13, TType.LIST, 'cartActualPosition', (TType.DOUBLE, None, False), None, ),  # 13
    (14, TType.LIST, 'cartActualVelocity', (TType.DOUBLE, None, False), None, ),  # 14
    (15, TType.LIST, 'cartActualAccelera', (TType.DOUBLE, None, False), None, ),  # 15
    (16, TType.LIST, 'slaveReady', (TType.BOOL, None, False), None, ),  # 16
    (17, TType.BOOL, 'collision', None, None, ),  # 17
    (18, TType.BYTE, 'collisionAxis', None, None, ),  # 18
    (19, TType.BOOL, 'emcStopSignal', None, None, ),  # 19
    (20, TType.BYTE, 'robotState', None, None, ),  # 20
    (21, TType.I32, 'robotError', None, None, ),  # 21
)
all_structs.append(IOStatus)
IOStatus.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'analogCurrentOutputs', (TType.DOUBLE, None, False), None, ),  # 1
    (2, TType.LIST, 'analogVoltageOutputs', (TType.DOUBLE, None, False), None, ),  # 2
    (3, TType.LIST, 'digitalInputs', (TType.BOOL, None, False), None, ),  # 3
    (4, TType.LIST, 'digitalOutputs', (TType.BOOL, None, False), None, ),  # 4
    (5, TType.LIST, 'toolIOIn', (TType.BOOL, None, False), None, ),  # 5
    (6, TType.LIST, 'toolIOOut', (TType.BOOL, None, False), None, ),  # 6
    (7, TType.LIST, 'toolButton', (TType.BOOL, None, False), None, ),  # 7
)
fix_spec(all_structs)
del all_structs
