papjia_melon_device:
  ros__parameters:
    service_gripper_control: "/papjia/melon/device/gripper/control"
    service_shears_control: "/papjia/melon/device/shears/control"
    serial_gripper: "/dev/ttyACM1"
    serial_shears: "/dev/ttyACM0"