papjia_line_tracing_node:
  ros__parameters:
    topic_image: /gazebo/camera/image_raw
    topic_camera_info: /gazebo/camera/camera_info
    pose_camera2base:
      [
        0.502431315754795,
        -0.005714542810736592,
        0.26511741831834806,
        0.0,
        1.57,
        0.0,
      ]
    pose_left2right:
      [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, -1.5707963267948966]
    save_folder: /home/yw/Documents/images
    save_image: false
    show_image: true
    roi: [20, 330, 1900, 600]
    centerline: [960, 1, 960, 1078] # [x1, y1, x2, y2], 保证中线与y轴（像素轴）平行
    use_maskrcnn: false
    wheel_separation: 0.6
    car_speed: 0.05
    enable_adjust_speed: true
    topic_tracing_trigger: /papjia/move/line_tracing_trigger
    pid: [0.05, 0.005, 0.02]
    update_hz: 4.0
    use_stamp_twist: false
